### ISSUE TITLE
How to use this with react-map-gl? Error: Terra Draw is not enabled

### ISSUE THREAD

**Issue by marisancans** [JamesLMilner/terra-draw#172] opened 2024-01-21 15:50 UTC
Hi, im trying to create polygon drawing using react-map-gl library in nextjs. Im getting not enabled error and im not sure why?

Here is how im trying to do it now:

```
import React, { useRef } from "react";

import "maplibre-gl/dist/maplibre-gl.css";

import Map from "react-map-gl/maplibre";

import { useMap } from "react-map-gl";

import { useContext } from "react";
import { ExplorePageContext } from "~/components/explore/pageContext";

import { MapLibreGL as lib } from "maplibre-gl";
import {
  TerraDraw,
  TerraDrawMapLibreGLAdapter,
  TerraDrawCircleMode,
  TerraDrawPolygonMode,
} from "terra-draw";

const terraDrawSetup = (map) => {
  if (!map) return;

  // Create Terra Draw
  const draw = new TerraDraw({
    // Using the MapLibre Adapter
    adapter: new TerraDrawMapLibreGLAdapter({ map, lib }),

    // Add the Rectangle Mode
    modes: [new TerraDrawPolygonMode(), new TerraDrawCircleMode()],
  });

  // Enable Terra Draw
  draw.setMode("draw_polygon");

  return draw;
};

const C = () => {
  const { current: map } = useMap();

  const m = map.getMap();
  console.log("m", m);
  const draw = terraDrawSetup(m);
  console.log("draw", draw);
};

const GlMap = ({ children }) => {
  const { routes } = useContext(ExplorePageContext);

  console.log("MAP RENDER");

  const mapStyle = {
    version: 8,
    sources: {
      osm: {
        type: "raster",
        tiles: [
          "https://tiles.stadiamaps.com/tiles/alidade_smooth_dark/{z}/{x}/{y}.png",
        ],
        tileSize: 256,
        attribution: "&copy; OpenStreetMap Contributors",
        maxzoom: 19,
      },
    },
    layers: [
      {
        id: "osm",
        type: "raster",
        source: "osm",
      },
    ],
  };

  return (
    <Map
      initialViewState={{
        latitude: 56.948719,
        longitude: 24.108638,
        zoom: 10,
      }}
      mapStyle={mapStyle}
      attributionControl={false}
    >
      {children}
      <C />
    </Map>
  );
};

export default GlMap;

```
```

{
  "name": "web",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "build": "next build",
    "dev": "next dev",
    "generate": "npx prisma generate",
    "postinstall": "prisma generate",
    "lint": "next lint",
    "start": "next start"
  },
  "dependencies": {
    "@hookform/resolvers": "^3.3.1",
    "@next-auth/prisma-adapter": "^1.0.7",
    "@prisma/client": "^5.1.1",
    "@radix-ui/react-alert-dialog": "^1.0.4",
    "@radix-ui/react-dialog": "^1.0.5",
    "@radix-ui/react-icons": "^1.3.0",
    "@radix-ui/react-label": "^2.0.2",
    "@radix-ui/react-navigation-menu": "^1.1.4",
    "@radix-ui/react-popover": "^1.0.7",
    "@radix-ui/react-radio-group": "^1.1.3",
    "@radix-ui/react-scroll-area": "^1.0.5",
    "@radix-ui/react-select": "^1.2.2",
    "@radix-ui/react-separator": "^1.0.3",
    "@radix-ui/react-slot": "^1.0.2",
    "@radix-ui/react-switch": "^1.0.3",
    "@radix-ui/react-toast": "^1.1.4",
    "@radix-ui/react-tooltip": "^1.0.7",
    "@radix-ui/themes": "^1.1.2",
    "@reduxjs/toolkit": "^1.9.5",
    "@routingjs/valhalla": "^0.1.0",
    "@t3-oss/env-nextjs": "^0.3.1",
    "@tanstack/react-table": "^8.9.7",
    "@trpc/client": "^10.38.1",
    "@trpc/next": "^10.38.1",
    "@trpc/server": "^10.38.1",
    "@types/mapbox-gl": "^2.7.19",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.0.0",
    "echarts-for-react": "^3.0.2",
    "embla-carousel-react": "^8.0.0-rc19",
    "leaflet": "^1.9.4",
    "lodash": "^4.17.21",
    "lucide-react": "^0.276.0",
    "mapbox-gl": "^3.1.0",
    "maplibre-gl": "^3.6.2",
    "next": "^13.4.2",
    "next-auth": "^4.22.4",
    "next-redux-wrapper": "^8.1.0",
    "next-themes": "^0.2.1",
    "protomaps": "^1.23.1",
    "react": "^18.2.0",
    "react-color": "^2.19.3",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.45.4",
    "react-icons": "^4.10.1",
    "react-map-gl": "^7.1.7",
    "react-number-format": "^5.3.1",
    "react-photoswipe-gallery": "^3.0.1",
    "react-redux": "^8.1.2",
    "react-resizable-panels": "^1.0.7",
    "react-resize-detector": "^9.1.0",
    "react-responsive": "^9.0.2",
    "react-select": "^5.8.0",
    "superjson": "^1.13.1",
    "tailwind-merge": "^1.14.0",
    "tailwindcss-animate": "^1.0.6",
    "terra-draw": "^0.0.1-alpha.54",
    "vaul": "^0.8.0",
    "zod": "^3.22.2"
  },
  "devDependencies": {
    "@types/eslint": "^8.37.0",
    "@types/leaflet": "^1.9.8",
    "@types/lodash": "^4.14.200",
    "@types/node": "^18.16.0",
    "@types/prettier": "^2.7.2",
    "@types/react": "^18.2.6",
    "@types/react-color": "^3.0.11",
    "@types/react-dom": "^18.2.4",
    "@types/uuid": "^9.0.7",
    "@typescript-eslint/eslint-plugin": "6.0.0",
    "@typescript-eslint/parser": "6.0.0",
    "add": "^2.0.6",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.40.0",
    "eslint-config-next": "^13.4.2",
    "or": "^0.2.0",
    "postcss": "^8.4.27",
    "prettier": "^2.8.8",
    "prettier-plugin-tailwindcss": "^0.2.8",
    "prisma": "^5.1.1",
    "tailwindcss": "^3.3.3",
    "typescript": "^5.0.4",
    "yarn": "^1.22.19"
  },
  "ct3aMetadata": {
    "initVersion": "7.18.0"
  }
}

```

**Comment by JamesLMilner** [comment] 2024-01-21 16:37
Hey @marisancans I'm just on my phone at the moment, but just looking at the code I think you need to call draw.start() before calling draw.setMode()

Let me know if this helps?

**Comment by marisancans** [comment] 2024-01-21 16:48
ok, that helps and Im moving forward. 
After adding
```
  if (draw) {
    draw.start();
    draw.setMode("polygon");
  }
```

Now im getting this error that is outputted twice in console. 
Not sure what causes this now
```

Unhandled Runtime Error
Error: Source "td-point" already exists.

Call Stack
se.addSource
node_modules/maplibre-gl/dist/maplibre-gl.js (35:111068)
Ba.Map.addSource
node_modules/maplibre-gl/dist/maplibre-gl.js (35:364652)
a._addGeoJSONSource
node_modules/terra-draw/dist/terra-draw.modern.js (1:14056)
a._addGeoJSONLayer
node_modules/terra-draw/dist/terra-draw.modern.js (1:15254)
eval
node_modules/terra-draw/dist/terra-draw.modern.js (1:17824)
```

**Comment by JamesLMilner** [comment] 2024-01-21 17:22
I think this looks like multiple instances of Terra Draw are being created. You should only create one instance of Terra Draw with React, using useMemo or similar hooks.

Can you try doing that and see how you get on?

**Comment by marisancans** [comment] 2024-01-21 17:31
ok it seems that useRef helps and its working for me now.
I will try to read docs on how to edit the polygons now.
Thank you for help, I was really stuck here.
I previously used react leaflet but it really breaks because of nextjs SSR and so far terra-draw + Libre maps combo works great!


```

const C = () => {
  const { current: map } = useMap();
  const drawRef = useRef(null);

  const m = map.getMap();
  console.log("m", m);

  useEffect(() => {
    if (!drawRef.current) {
      drawRef.current = terraDrawSetup(m);
      console.log("draw", drawRef.current);
    }
  }, [m]);
};
```

**Comment by marisancans** [comment] 2024-01-21 18:34
@JamesLMilner 
Hi, sorry for bothering again
Im unable to get a simple event to work
It works if I dont use addFeatures
I want to load existing geoJson features from API with the ability to edit them and add new ones. 


```

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'setData')

Call Stack
a._setGeoJSONLayerData
node_modules/terra-draw/dist/terra-draw.modern.js (1:15369)
eval
node_modules/terra-draw/dist/terra-draw.modern.js (1:17641)
```
```

const terraDrawSetup = (map) => {
  if (!map) return;

  // Create Terra Draw
  const draw = new TerraDraw({
    // Using the MapLibre Adapter
    adapter: new TerraDrawMapLibreGLAdapter({ map, lib }),

    // Add the Rectangle Mode
    modes: [
      new TerraDrawPolygonMode(),
      new TerraDrawSelectMode({
        flags: {
          polygon: {
            feature: {
              // The entire Feature can be moved
              draggable: true,

              // Individual coordinates that make up the Feature...
              coordinates: {
                // Can be added
                midpoints: true,

                // Can be moved
                draggable: true,

                // Can be deleted
                deletable: true,
              },
            },
          },
        },
      }),
    ],
  });

  draw?.on("finish", (ids: string[]) => {
    console.log("finish", ids);
  });

  draw.start();
  draw.setMode("polygon");

  draw?.addFeatures([
    {
      type: "Feature",
      geometry: {
        type: "Polygon",
        coordinates: [
          [
            [24.108638, 56.948719],
            [24.109638, 56.948719],
            [24.109638, 56.949719],
            [24.108638, 56.949719],
            [24.108638, 56.948719],
          ],
        ],
      },
      properties: {
        mode: "polygon",
      },
    },
  ]);

  return draw;
};
```

**Comment by JamesLMilner** [comment] 2024-01-21 18:43
I will try and debug when I'm back but I think you need to wait for the map to be fully loaded before adding Terra Draw - does react-map-gl support some sort of on ready callback ? If so you could set the Terra Draw instance in there

**Comment by marisancans** [comment] 2024-01-21 18:59
Spot on again!
If anyone else has this problem, i solved it with on load event
```
const C = () => {
  const { current: map } = useMap();
  const drawRef = useRef(null);

  const m = map.getMap();
  console.log("m", m);

  useEffect(() => {
    m.on("load", () => {
      console.log("load");
      if (!drawRef.current) {
        const draw = terraDrawSetup(m);

        if (!draw) return;

        drawRef.current = draw;
        console.log("draw", drawRef.current);
      }
    });
  }, [m]);
};
```


In order for me to both support editing and adding new polygons I have somehow switch between these modes right?
Like a button or something
```
export enum ModeTypes {
	Drawing = "drawing",
	Select = "select",
	Static = "static",
	Render = "render",
}
```

**Comment by marisancans** [comment] 2024-01-21 20:01
guides/2.STORE.md looks like its outdated
```

// Later on, perhaps after the user has refreshed.
const retrievedFeatures = localStorage.getItem('terra-draw-data');
if (retrievedFeatures) {
  draw.setFeatures(JSON.parse(retrievedFeatures)) <----- setFeatures doesnt exist, maybe its addFeatures?
}
```

**Comment by JamesLMilner** [comment] 2024-01-22 21:11
Hey @marisancans - yes you can switch modes with `setMode` method. Use the `name` property from this list to swap to the mode you want (assuming you have created the mode and passed it to the modes array at startup.

You are right the `setFeature` line is wrong. I will update it!

**Comment by JamesLMilner** [comment] 2024-01-22 21:21
@marisancans what are you building out of interest? :)

**Comment by marisancans** [comment] 2024-01-23 07:37
> @marisancans what are you building out of interest? :)

A platform that scrapes real estate ads and displays them better. With routes to your work, polygon filter that lets you only query estates in that area. So far, terra-draw has been the fastest way for me to implement all this. Component rendering and remounting is still a bit of a hustle having to use refs (not that familiar with it and code looks ugly). Thank you for building this. I will keep this issue open for a bit in case I have some more questions if you dont mind?

**Comment by marisancans** [comment] 2024-01-23 20:15
@JamesLMilner Is there a way where when in mode "polygon", when I click on an existing polygon I select it and switch mode to "select"? I hate to have implement a switch, its not user friendly I think

**Comment by JamesLMilner** [comment] 2024-01-26 19:17
Hey @marisancans thanks for sharing your usecase/expected behaviour here. The issue is that some people might expect that to draw another polygon inside the existing polygon if `allowSelfIntersections` was true. 

I think it might make sense to close this issue just to avoid it covering too many different topics if that's okay. If you want to create a new issue specifically about this I'd be happy to discuss specific ways to make that happen. We might to allow for this somehow, either via a flag or maybe via allowing custom callbacks on click somehow. Let's keep discussing on another dedicated issue!

**Closed by JamesLMilner** 2024-01-26 19:17 UTC
Labels: question
