### ISSUE TITLE
[Bug] Select should choose Point and LineString over Polygon

### ISSUE THREAD

**Issue by ScottEAdams** [JamesLMilner/terra-draw#268] opened 2024-07-03 01:46 UTC
**Describe the bug**
If you draw some points and then draw a polygon over those points (or vice versa), it is impossible to then select the points.

**Terra Draw npm version**
alpha.68

**To Reproduce**
1. Go to terradraw.io
2. Draw some points and a polygon over the top
3. Try to select the points

**Expected behavior**
I would expect that when clicking exactly on a point that it is the point that is selected. Similar for linestring.

**Screenshots**
[scrnli_03_07_2024_03-40-49.webm](https://github.com/JamesLMilner/terra-draw/assets/624154/33af2df3-c6da-4b88-aa06-3f7a837bbb36)

**Comment by ScottEAdams** [comment] 2024-07-03 02:06
I did a little playing around and although not perfect, I think an improvement is to check the type of features in featuresAtMouseEvent in select.mode.ts and prioritise Point then LineString then Polygon.

**Comment by JamesLMilner** [comment] 2024-07-06 20:20
Hey @ScottEAdams thanks for raising this. I think you are right here in that the points should be selectable as they are layered on top of (z-indexed) above the polygon. I think I know what the problem is which is basically when we loop through the closest geometries, if the click is inside the polygon it always gets considered the 'closest' geometry. I will eventually look at fixing this when I get a moment. Let me know if you have any questions.

**Comment by JamesLMilner** [comment] 2024-08-30 10:35
This is fixed in the `main` branch and will come out in the next release!

**Closed by JamesLMilner** 2024-08-30 10:35 UTC
Labels: bug, help wanted, good first issue
