### ISSUE TITLE
Drawing on mobile devices

### ISSUE THREAD

**Issue by basaran** [JamesLMilner/terra-draw#203] opened 2024-02-29 16:06 UTC
Hello, 

#153 reports drawing on mobile works, but I failed at my attempts during development and terradraw.io.

I tried disabling leaflet dragging yet it still didn't work. Could you please clarify if drawing (freehand, circle, rectangle) would work on mobile devices?

**Comment by JamesLMilner** [comment] 2024-03-02 00:23
Hey @basaran thanks for raising this issue - drawing for points, lines and polygons should work as intended for mobile. There is an open issue for documenting which modes work or not on mobile, #107. 

Circle and rectangle 'work' but the UX is a little clunky.

Here's it working on terradraw.io for me:

![IMG_20240302_001938.jpg](https://github.com/JamesLMilner/terra-draw/assets/8822075/b5794c2c-c2b4-40e8-9dd5-fa81ae1c0a86)

Can you elaborate what is not working for you exactly and I will try to help? Thanks!

**Comment by JamesLMilner** [comment] 2024-03-02 00:24
Hey @basaran thanks for raising this issue - drawing for points, lines and polygons should work as intended for mobile. There is an open issue for documenting which modes work or not on mobile, #107. 

Circle and rectangle 'work' but the UX is a little clunky.

Here's it working on terradraw.io for me:

![IMG_20240302_001938.jpg](https://github.com/JamesLMilner/terra-draw/assets/8822075/b5794c2c-c2b4-40e8-9dd5-fa81ae1c0a86)

Can you elaborate what is not working for you exactly and I will try to help? Thanks!

**Comment by JamesLMilner** [comment] 2024-03-11 22:25
Hey @basaran, going to close this one out to keep the issues in check. Feel free to open another issue if you are still having any problems!

**Closed by JamesLMilner** 2024-03-11 22:25 UTC
Labels: question, awaiting feedback
